apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmer-portal
  namespace: platform
  labels:
    app: farmer-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farmer-portal
  template:
    metadata:
      labels:
        app: farmer-portal
    spec:
      containers:
        - name: farmer-portal
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: ecr-secret
